#!/usr/bin/env bash

info() {
    echo -e "\e[42mINFO:"$*"\e[49m"
}

errors=0
error() {
    echo -e "\e[41mERROR:"$*"\e[49m"
    let "errors++"
}

checkError() {
    if [[ $? != 0 ]]; then
        error "An error occurred $*"
    fi
}

os=$(uname -s)
cpu=$(uname -m)

info "OS is $os"
info "CPU is $cpu"

# Linux
if [[ "$os" == "Linux" ]]; then

    # if [[ $UID != 0 ]]; then
    #     error "Please run as sudo!"
    #     exit 1
    # fi

    # Below doesn't fix the problem, we need to have the dependencies cross compiiled or downloaded from somewhere smh

    # sudo ln -s /usr/lib/x86_64-linux-gnu/libasound.so /usr/lib/aarch64-linux-gnu/libasound.so

    # sudo ln -s /usr/lib/x86_64-linux-gnu/libjack.so /usr/lib/aarch64-linux-gnu/libjack.so

    if [[ -d "/usr/include/alsa" ]]; then
        info "Compiling for ALSA"

        outdir="./libs/alsa-"$cpu""
        mkdir -p "$outdir"

        info "Compiling source files for ALSA"

        g++ -Wall -c -fPIC -D__LINUX_ALSA__ rtmidi_c.cpp RtMidi.cpp -lasound -lpthread

        checkError "Compiling source files for ALSA"

        info "Creating library for ALSA"

        g++ -Wall -shared -fPIC -D__LINUX_ALSA__ -o "$outdir/librtmidi.so" rtmidi_c.o RtMidi.o -lasound -lpthread

        checkError "Creating library for ALSA"

        rm rtmidi_c.o RtMidi.o

        if [[ ! -z $(command -v arm-linux-gnueabihf-g++-8) ]]; then

            outdir="./libs/alsa-arm"
            mkdir -p "$outdir"

            info "Cross compiling source files for ALSA arm"

            arm-linux-gnueabihf-g++-8 -Wall -c -fPIC -D__LINUX_ALSA__ rtmidi_c.cpp RtMidi.cpp -lasound -lpthread

            checkError "Cross compiling source files for ALSA arm"

            info "Creating library for ALSA arm"

            arm-linux-gnueabihf-g++-8 -Wall -shared -fPIC -D__LINUX_ALSA__ -o "$outdir/librtmidi.so" rtmidi_c.o RtMidi.o -lasound -lpthread

            checkError "Creating library for ALSA arm"

            rm rtmidi_c.o RtMidi.o

        else
            error "Could not cross compile for ALSA arm, missing arm-linux-gnueabihf-g++-8"
        fi

        if [[ ! -z $(command -v aarch64-linux-gnu-g++-8) ]]; then

            outdir="./libs/alsa-aarch64"
            mkdir -p "$outdir"

            info "Cross compiling source files for ALSA aarch64"

            aarch64-linux-gnu-g++-8 -Wall -c -fPIC -D__LINUX_ALSA__ rtmidi_c.cpp RtMidi.cpp -lasound -lpthread

            checkError "Cross compiling source files for ALSA aarch64"

            info "Creating library for ALSA aarch64"

            aarch64-linux-gnu-g++-8 -Wall -shared -fPIC -D__LINUX_ALSA__ -o "$outdir/librtmidi.so" rtmidi_c.o RtMidi.o -lasound -lpthread

            checkError "Creating library for ALSA aarch64"

            rm rtmidi_c.o RtMidi.o

        else
            error "Could not cross compile for ALSA aarch64, missing aarch64-linux-gnu-g++-8"
        fi

    else
        error "Alsa headers not found!"
        error "Run sudo apt install libasound2-dev"
    fi

    if [[ -d "/usr/include/jack" ]]; then
        info "Compiling for ALSA + JACK"

        outdir="./libs/alsa-jack-"$cpu""
        mkdir -p "$outdir"

        info "Compiling source files for ALSA + JACK"

        g++ -Wall -c -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ rtmidi_c.cpp RtMidi.cpp -lasound -lpthread -ljack

        checkError "Compiling source files for ALSA + JACK"

        info "Creating library for ALSA + JACK"

        g++ -Wall -shared -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -o "$outdir/librtmidi.so" rtmidi_c.o RtMidi.o -lasound -lpthread -ljack

        checkError "Creating library for ALSA + JACK"

        rm rtmidi_c.o RtMidi.o

        if [[ ! -z $(command -v arm-linux-gnueabihf-g++-8) ]]; then

            outdir="./libs/alsa-jack-arm"
            mkdir -p "$outdir"

            info "Cross compiling source files for ALSA + JACK arm"

            arm-linux-gnueabihf-g++-8 -Wall -c -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ rtmidi_c.cpp RtMidi.cpp -lasound -lpthread -ljack

            checkError "Cross compiling source files for ALSA + JACK arm"

            info "Creating library for ALSA + JACK arm"

            arm-linux-gnueabihf-g++-8 -Wall -shared -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -o "$outdir/librtmidi.so" rtmidi_c.o RtMidi.o -lasound -lpthread -ljack

            checkError "Creating library for ALSA + JACK arm"

            rm rtmidi_c.o RtMidi.o

        else
            error "Could not cross compile for ALSA + JACK arm, missing arm-linux-gnueabihf-g++-8"
        fi

        if [[ ! -z $(command -v aarch64-linux-gnu-g++-8) ]]; then

            outdir="./libs/alsa-jack-aarch64"
            mkdir -p "$outdir"

            info "Compiling source files for ALSA + JACK aarch64"

            aarch64-linux-gnu-g++-8 -Wall -c -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ rtmidi_c.cpp RtMidi.cpp -lasound -lpthread -ljack

            checkError "Compiling source files for ALSA + JACK aarch64"

            info "Creating library for ALSA + JACK aarch64"

            aarch64-linux-gnu-g++-8 -Wall -shared -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -o "$outdir/librtmidi.so" rtmidi_c.o RtMidi.o -lasound -lpthread -ljack

            checkError "Creating library for ALSA + JACK aarch64"

            rm rtmidi_c.o RtMidi.o

        else
            error "Could not cross compile for ALSA + JACK aarch64, missing aarch64-linux-gnu-g++-8"
        fi

    else
        error "Jack headers not found!"
        error "Run sudo apt install libjack-jackd2-dev"
    fi
fi

# Darwin
if [[ "$os" == "Darwin" ]]; then

    # TODO check if headers are found

    info "Compiling for CoreMIDI"

    outdir="./libs/core-"$cpu""
    mkdir -p "$outdir"

    info "Compiling source files"

    g++ -Wall -c -fPIC -D__MACOSX_CORE__ rtmidi_c.cpp RtMidi.cpp -framework CoreMIDI -framework CoreAudio -framework CoreFoundation

    checkError "Compiling source files"

    info "Creating library"

    g++ -Wall -shared -dylib -fPIC -D__MACOSX_CORE__ -o "$outdir/librtmidi.dylib" rtmidi_c.o RtMidi.o -framework CoreMIDI -framework CoreAudio -framework CoreFoundation

    checkError "Creating library"

    rm rtmidi_c.o RtMidi.o

    # TODO CoreMIDI + JACK

    # /usr/local/include/jack
    # install headers using brew install jack

fi

# MinGw
if [[ "$os" == "MinGw" ]]; then
    info "Compiling for MinGw"
    # TODO
fi

info "Finished with "$errors" errors"
info "Output will be found in ./libs"
